# Generated by Django 6.0.4 on 2026-04-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField()),
                ('trabajo', models.CharField(choices=[('mecanica', 'Mecánica'), ('electrico', 'Eléctrico'), ('aire', 'Aire acondicionado'), ('latoneria', 'Latonería'), ('pintura', 'Pintura')], max_length=20)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
    ]
