# Generated by Django 6.0.4 on 2026-05-10 12:52

import crud_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_producto_options_alter_vehiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('codigo', models.CharField(default=crud_app.models._generar_codigo, max_length=6)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Código de verificación',
                'verbose_name_plural': 'Códigos de verificación',
            },
        ),
    ]
