# Generated by Django 6.0.4 on 2026-05-10 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_codigoverificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=6)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('servicio', models.CharField(choices=[('mecanica', 'Mecánica'), ('electrico', 'Eléctrico'), ('aire', 'Aire acondicionado'), ('latoneria', 'Latonería'), ('pintura', 'Pintura')], max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del problema')),
                ('fecha_pedida', models.DateField()),
                ('hora_pedida', models.TimeField()),
                ('fecha_admin', models.DateField(blank=True, null=True)),
                ('hora_admin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('espera', 'En espera'), ('agendada', 'Agendada'), ('reprogramada', 'Reprogramada — pendiente cliente'), ('confirmada', 'Confirmada por cliente'), ('rechazada', 'Rechazada por cliente')], default='espera', max_length=20)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creada_el'],
            },
        ),
    ]
