# Generated by Django 6.0.4 on 2026-05-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_alter_solicitud_options_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_usados', to='crud_app.solicitud'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='crud_app.producto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('agendada', 'Agendada'), ('reprogramada', 'Reprogramada — pendiente cliente'), ('confirmada', 'Confirmada por cliente'), ('rechazada', 'Rechazada por cliente'), ('terminada', 'Servicio terminado')], default='espera', max_length=20),
        ),
    ]
